project:
  type: website
  resources: 
    - "*.html" 
    - "*.pdf" 

website:
  title: "Air quality advisories"
  repo-url: https://github.com/bcgov/nr-epd-aq-statements
  repo-actions: [source, issue]
  navbar:
    search: true
    right:  
      - measuring.qmd
  sidebar:
    style: "docked"
    alignment: left
    border: true
    contents:
      - section: Active advisories
        contents: statements/*
      - text: Historical advisories
        href: statements.qmd
      - section: More Topics
        contents:
          - text: "Air Quality Data"
            href: https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality
            contents:
            - text: "Air advisories"
              href: #
          - text: "Air Quality Subscription Service"
            href: https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/air-advisories/air-quality-subscription-service
          - text: "Air Quality Health Index"
            href: https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/aqhi
          - text: "Air Quality Health Index widget"
            href: https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/aghi-widget
          - text: "Latest air quality data"
            href: https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/current-air-quality-data
          - text: "How we measure"
            href: https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/measuring

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true






