---
title: "Air quality warnings"
toc: false
listing:
  - id: aq-warnings
    template: _aqw_listing.ejs
    contents:
      - ./_recent_warnings.yaml
    sort: "date desc"
---

## Issued warnings

::: {#aq-warnings}
:::

## Latest updates

{{< callout_start >}}

**For the latest updates**:

- Subscribe to the [Air Quality Subscription Service](https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/air-advisories/air-quality-subscription-service)
- Outside regular business hours, visit [Environment and Climate Change Canada’s Public Weather Alerts for B.C.](https://weather.gc.ca/?province=bc&zoom=5&alertTableFilterProv=BC)
- Visit [Metro Vancouver’s Air Quality Data and Warnings](https://metrovancouver.org/services/air-quality-climate-action/air-quality-data-and-advisories) for information about **Metro Vancouver** and parts of the **Fraser Valley Regional District** (see [regions in AirMap](https://gis.metrovancouver.org/maps/Air))

{{< callout_end >}}


## About air quality warnings

Air quality warnings are issued when pollution levels in the air have reached, or are expected to reach, levels that may pose health risks.

Warnings are issued to:

- inform the public when air quality is degraded
- help people make informed choices to reduce their exposure to elevated air pollution levels
- provide vulnerable individuals and the general public with health advice developed by BC health agencies

Warnings are colour‑coded according to the level of health risk. Yellow warnings indicate conditions where impacts are expected to be moderate, localized, or short‑term. Orange warnings are less frequent and indicate conditions where impacts may be major or widespread. The information and health advice are tailored to each warning level.

Warnings, other than those driven by wildfire smoke, may also trigger emission reduction actions (such as industrial emissions or wood stove use) when specified by provincial waste discharge authorizations and local government bylaws.
