project:
  type: website
  resources: 
    - "*.html" 
    - "*.pdf" 

website:
  title: "Air Quality Statements" 
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]  
  navbar:
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Air quality advisories
      - href: measuring.qmd
        text: How we measure

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



