project:
  type: website
  resources: 
    - "*.html" 
    - "*.pdf" 

website:
  title: "Air Quality Statements" 
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - measuring.qmd
  sidebar:
    style: "docked"
    search: true
    contents: statements/*

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



