name: Deploy PR to Github Pages

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Quarto
        if: github.event.action != 'closed'
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Quarto Project
        if: github.event.action != 'closed'
        shell: bash
        run: |
          quarto render . --output-dir ./pr-preview/pr-${{ github.event.pull_request.number }}
        
        
      - name: Deploy to/Cleanup GitHub Pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./frontend/pr-preview/pr-${{ github.event.pull_request.number }}
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
